---
# eslint配置参考：http://eslint.org/docs/user-guide/configuring
env:
  browser: true
globals:
  require: true
  window: true
  document: true
# eslint-config-airbnb：https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
# airbnb的javascript标准样式：https://github.com/airbnb/javascript
extends: eslint-config-airbnb
parser: babel-eslint
rules:
  array-callback-return: off
  arrow-body-style: warn
  comma-dangle: off
  class-methods-use-this: off
  consistent-return: off
  eol-last: off
  import/prefer-default-export: off
  jsx-a11y/no-static-element-interactions: off
  # http://eslint.org/docs/rules/max-len
  max-len:
  - error
  - 120
  # 排除注释、字符串、url、js模板
  - ignoreComments: true
    ignoreStrings: true
    ignoreUrls: true
    ignoreTemplateLiterals: true
  no-param-reassign: off
  no-else-return: off
  no-plusplus: off
  prefer-template: off
  react/jsx-no-bind: off
  react/prefer-es6-class: off
  react/sort-comp: off
  react/no-multi-comp: off
  react/no-did-mount-set-state: off
  react/forbid-prop-types: off
  react/jsx-no-target-blank: off
  react/jsx-filename-extension: off
  no-unused-expressions: off
  global-require: off
